name: Terragrunt Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      AWS_REGION: us-east-1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install and configure AWS CLI
      run: |
        aws --version
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region $AWS_REGION

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    - name: Install Terragrunt
      run: |
        TERRAGRUNT_VERSION=$(curl --silent https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        sudo curl --location "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64" --output /usr/local/bin/terragrunt
        sudo chmod +x /usr/local/bin/terragrunt
      
    # - name: Initialize Terragrunt
    #   run: |
    #     cd prod/us-east-1/
    #     terragrunt init
        
    - name: Plan Terraform changes
      id: plan
      run: |
        cd prod/us-east-1/
        terragrunt run-all plan --terragrunt-source-update
        
    - name: Apply Terraform changes
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      run: |
        cd prod/us-east-1/
        terragrunt apply-all --terragrunt-source-update -auto-approve
